# Generated by Django 3.1.4 on 2020-12-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20201213_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_tbl',
            name='cp_img',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
    ]
