# Generated by Django 3.1.4 on 2020-12-15 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_goods_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_tbl',
            name='gd_category',
            field=models.CharField(blank=True, choices=[('밥류', '밥류'), ('샌드위치류', '샌드위치류'), ('샐러드류', '샐러드류'), ('누들류', '누들류'), ('기타', '기타')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='order_tbl',
            fields=[
                ('od_no', models.AutoField(primary_key=True, serialize=False)),
                ('od_number', models.IntegerField(blank=True, null=True)),
                ('od_join', models.DateField(auto_now_add=True)),
                ('od_zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('od_address', models.CharField(blank=True, max_length=200, null=True)),
                ('od_address_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('od_state', models.BooleanField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gd_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.goods_tbl')),
            ],
        ),
    ]
