# Generated by Django 3.1.4 on 2020-12-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_shipper_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tbl',
            name='sp_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.shipper_tbl'),
        ),
    ]
